### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by benhovinga** [open-volunteer/open-volunteer#8]
Need a logo for this project. Maybe get it commissioned on fiverr?

**Comment by mirzazulfan** [comment]
Hi @benhovinga I've designed a logo, what do you think? If you need something else please let me know. the logo idea is Letters O, V and connecting peoples. Best Regard.
![open volunter](https://user-images.githubusercontent.com/36124339/54896677-f2dd7880-4ef7-11e9-859b-1d721876c11e.png)

**Comment by benhovinga** [comment]
Oh wow! I didn't expect a response on this so soon. @mirzazulfan I like it a lot. The colours I am not sure of yet until I get the theme in place, but the design looks amazing. Do you often design logos for small projects? Now do you license it?

**Comment by mirzazulfan** [comment]
Thanks for your response @benhovinga . I often make logos for open source projects for free. what color do you like? I'm really happy to help open source project. :) 

#### Licence
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

**Comment by benhovinga** [comment]
@mirzazulfan you are a good person for doing that. Is it possible to get the source files and I can pick the colour later? I know just enough with Illustrator to change colours in a vector. I'll make sure to add the CC-BY-4.0 for the logo as well.

**Comment by mirzazulfan** [comment]
Hi @benhovinga Im glad you liked it. You can download all editables file here https://drive.google.com/drive/folders/1c5x080pQ2ikHBoPw8X4Wh1UrDc9tdoK6
Best Regard.

**Comment by benhovinga** [comment]
@mirzazulfan thank you so much. I will put this in the next commit when I get the chance. I will add it to the theme when I get one setup.

**Comment by benhovinga** [comment]
Commit 907af8977bd1c61250db0feb0d646a15d92e64fd closes this issue.
